-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgNrae6TulOiskTLyS
viRU6ritNKlUbGDPsLaWtahcehmgCgYIKoZIzj0DAQehRANCAASNDwNBV+ZuVp1e
tGyQpVpcvizGZSqhc+8gsQfTEjYZr6E5gZLTTRDCXBA+Q5kU59RISK/oSk/dRQx3
YI175I4/
-----END PRIVATE KEY-----