# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

# This workflow will build, archive, and export a Swift project

name: Swift

on:
  push:
    branches: [ "branch1" ]
  pull_request:
    branches: [ "branch1" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set Up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0.1'
        
    - name: Install Dependencies
      run: |
        if [ -f "Podfile" ]; then
          gem install cocoapods
          pod install
        fi

    - name: Build and Archive
      run: |
        cd "AddressFull CI CD"
        xcodebuild clean archive \
          -workspace "AddressFull.xcworkspace" \
          -scheme AddressFull-Production \
          -sdk iphoneos \
          -archivePath ./build/AddressFull.xcarchive \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

    - name: Export IPA
      run: |
        cd "AddressFull CI CD"
        xcodebuild -exportArchive \
          -archivePath ./build/AddressFull.xcarchive \
          -exportOptionsPlist ./ExportOptions.plist \
          -exportPath ./build

    - name: Upload IPA as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: AddressFull-Production.ipa
        path: "AddressFull CI CD/build/*.ipa"

